// Generates src/fonts/roboto-vfs.ts: base64 Roboto Regular + Medium (no italics) taken from the
// installed pdfmake package. The file is its own module so bundlers emit it as a separate chunk
// (it is only reached through a dynamic import in src/fonts/index.ts).
//
// No subsetting: Roboto already covers Latin Extended-A and Cyrillic (PL + UK). Subsetting would
// need a build-time dependency (e.g. harfbuzz-wasm) and risks dropping glyphs used in invoices.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const fontsDir = new URL("../node_modules/pdfmake/build/fonts/Roboto/", import.meta.url);
const outFile = new URL("../src/fonts/roboto-vfs.ts", import.meta.url);
const files = ["Roboto-Regular.ttf", "Roboto-Medium.ttf"];

const entries = files.map((name) => {
  const b64 = readFileSync(new URL(name, fontsDir)).toString("base64");
  return `  "${name}": "${b64}",`;
});

const header = `// GENERATED by scripts/gen-fonts.mjs from pdfmake/build/fonts/Roboto (Apache-2.0, Google).
// Do not edit; run \`pnpm --filter @ksefuj/pdf gen:fonts\`.
`;
const body = `export const robotoVfs: Record<string, string> = {\n${entries.join("\n")}\n};\n`;

mkdirSync(new URL("../src/fonts/", import.meta.url), { recursive: true });
writeFileSync(outFile, header + body);
console.log(`wrote ${outFile.pathname} (${((header.length + body.length) / 1024).toFixed(0)} kB)`);
