// Generates THIRD_PARTY_NOTICES.md at the repository root from the installed packages:
// the vendored generator (licence file kept next to the code), Roboto (bundled font), and the
// production dependency closure of @ksefuj/pdf with each package's licence field and licence text.
//
// Run: pnpm --filter @ksefuj/pdf gen:notices   (after pnpm install)
import { existsSync, readFileSync, readdirSync, realpathSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const pkgDir = fileURLToPath(new URL("..", import.meta.url));
const repoRoot = join(pkgDir, "..", "..");
const ownPkg = JSON.parse(readFileSync(join(pkgDir, "package.json"), "utf8"));

// Manifests without a licence field: the licence was checked by hand in the package's repository.
const LICENSE_OVERRIDES = {
  "png-js": "MIT (manifest has no licence field; the LICENSE file in the package is MIT)",
};

function findPackage(name, fromDir) {
  let dir = fromDir;
  for (;;) {
    const candidate = join(dir, "node_modules", name, "package.json");
    if (existsSync(candidate)) {
      return dirname(realpathSync(candidate));
    }
    const parent = dirname(dir);
    if (parent === dir) {
      return undefined;
    }
    dir = parent;
  }
}

function licenseOf(manifest) {
  if (LICENSE_OVERRIDES[manifest.name]) {
    return LICENSE_OVERRIDES[manifest.name];
  }
  if (typeof manifest.license === "string") {
    return manifest.license;
  }
  if (manifest.license?.type) {
    return manifest.license.type;
  }
  if (Array.isArray(manifest.licenses)) {
    return manifest.licenses.map((l) => l.type).join(" OR ");
  }
  return "UNKNOWN";
}

function licenseText(dir) {
  const file = readdirSync(dir).find((name) => /^(licen[cs]e|copying)(\.(md|txt))?$/i.test(name));
  return file ? readFileSync(join(dir, file), "utf8").trim() : undefined;
}

function repositoryOf(manifest) {
  const repo =
    typeof manifest.repository === "string" ? manifest.repository : manifest.repository?.url;
  return (repo ?? manifest.homepage ?? "").replace(/^git\+/, "").replace(/\.git$/, "");
}

const found = new Map();
function visit(name, fromDir, optional) {
  const dir = findPackage(name, fromDir);
  if (!dir) {
    if (!optional) {
      throw new Error(`cannot resolve ${name} from ${fromDir}; run pnpm install`);
    }
    return;
  }
  const manifest = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
  const key = `${manifest.name}@${manifest.version}`;
  if (found.has(key)) {
    return;
  }
  found.set(key, { manifest, dir });
  for (const dep of Object.keys(manifest.dependencies ?? {})) {
    visit(dep, dir, false);
  }
  for (const dep of Object.keys(manifest.optionalDependencies ?? {})) {
    visit(dep, dir, true);
  }
}
for (const dep of Object.keys(ownPkg.dependencies)) {
  visit(dep, pkgDir, false);
}

const packages = [...found.values()].sort((a, b) => a.manifest.name.localeCompare(b.manifest.name));

const vendoredLicense = readFileSync(
  join(pkgDir, "vendor/ksef-pdf-generator/LICENSE"),
  "utf8",
).trim();

const lines = [];
lines.push("# Third-party notices", "");
lines.push(
  "ksefuj is licensed under Apache-2.0 (see `LICENSE`). The PDF visualisation (`packages/pdf`) ships",
  "the third-party software below. Generated by `pnpm --filter @ksefuj/pdf gen:notices` from the",
  "installed packages; do not edit by hand.",
  "",
);

lines.push("## Vendored: ksef-pdf-generator", "");
lines.push(
  "- Source: https://github.com/CIRFMF/ksef-pdf-generator, commit",
  "  `f59fc4e2addcf42c74b1674e7c1d534085bc3a84` (release 1.1.40), copied into",
  "  `packages/pdf/vendor/ksef-pdf-generator/` with local patches (see `VENDORED.md` there).",
  "- Licence: MIT, Copyright (c) 2025 CIRF (the upstream `package.json` says ISC; the LICENSE file",
  "  is MIT).",
  "",
  "```text",
  vendoredLicense,
  "```",
  "",
);

lines.push("## Bundled font: Roboto", "");
lines.push(
  "- Roboto Regular and Medium (TrueType), taken from the `pdfmake` package",
  "  (`build/fonts/Roboto`) and embedded in generated PDFs (subset by pdfkit).",
  "- Licence: Apache License 2.0, Copyright Google LLC.",
  "  https://www.apache.org/licenses/LICENSE-2.0 and https://github.com/googlefonts/roboto",
  "",
);

lines.push("## Production dependencies of @ksefuj/pdf", "");
lines.push("| Package | Version | Licence |", "| --- | --- | --- |");
for (const { manifest } of packages) {
  lines.push(`| ${manifest.name} | ${manifest.version} | ${licenseOf(manifest)} |`);
}
lines.push("");

lines.push("## Licence texts", "");
for (const { manifest, dir } of packages) {
  lines.push(`### ${manifest.name} ${manifest.version}`, "");
  const repo = repositoryOf(manifest);
  lines.push(`Licence: ${licenseOf(manifest)}${repo ? `. Source: ${repo}` : ""}`, "");
  const text = licenseText(dir);
  lines.push(
    "```text",
    text ?? "(no licence file in the published package; see the licence field above)",
    "```",
    "",
  );
}

writeFileSync(join(repoRoot, "THIRD_PARTY_NOTICES.md"), `${lines.join("\n")}\n`);
const unknown = packages.filter(({ manifest }) => licenseOf(manifest).startsWith("UNKNOWN"));
console.log(`wrote THIRD_PARTY_NOTICES.md: ${packages.length} packages, ${unknown.length} unknown`);
for (const { manifest } of unknown) {
  console.log(`  unknown licence: ${manifest.name}@${manifest.version}`);
}
