#!/usr/bin/env node
/* eslint-disable no-console */
/**
 * Schema Update Script for KSeF Validator
 *
 * Downloads the latest XSD schemas from official Polish Ministry of Finance servers
 * and updates the bundled schema files used by the validator.
 *
 * Usage:
 *   pnpm update-schemas
 *   tsx scripts/update-schemas.ts
 *
 * This script should be run manually when we want to ensure we have the latest
 * official schemas. It will:
 * 1. Fetch all schemas from crd.gov.pl
 * 2. Compare with existing schemas (show diff if changed)
 * 3. Update the bundled schema files
 * 4. Regenerate the schemas-data.ts file
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const currentFilename = fileURLToPath(import.meta.url);
const currentDirname = dirname(currentFilename);
const rootDir = join(currentDirname, "..");
const schemasDir = join(rootDir, "packages/validator/src/schemas");

// Type definitions
interface SchemaUrls {
  main: string;
  struktury: string;
  elementarne: string;
  kody: string;
}

interface SchemaFiles {
  main: string;
  struktury: string;
  elementarne: string;
  kody: string;
}

interface DiffResult {
  changed: boolean;
  type: "new" | "modified" | "unchanged";
  message: string;
}

interface Schemas {
  main: string;
  struktury: string;
  elementarne: string;
  kody: string;
}

// Official schema URLs from Polish Ministry of Finance
const SCHEMA_URLS: SchemaUrls = {
  main: "http://crd.gov.pl/wzor/2025/06/25/13775/schemat.xsd",
  struktury:
    "http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/DefinicjeTypy/StrukturyDanych_v10-0E.xsd",
  elementarne:
    "http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/DefinicjeTypy/ElementarneTypyDanych_v10-0E.xsd",
  kody: "http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/DefinicjeTypy/KodyKrajow_v10-0E.xsd",
} as const;

// Schema filenames
const SCHEMA_FILES: SchemaFiles = {
  main: "schemat.xsd",
  struktury: "StrukturyDanych_v10-0E.xsd",
  elementarne: "ElementarneTypyDanych_v10-0E.xsd",
  kody: "KodyKrajow_v10-0E.xsd",
} as const;

/**
 * Download a file from URL with proper error handling
 */
async function downloadFile(url: string, description: string): Promise<string> {
  console.log(`📥 Downloading ${description}...`);
  console.log(`   ${url}`);

  try {
    const response = await fetch(url);

    if (!response.ok) {
      throw new Error(`HTTP ${response.status} ${response.statusText}`);
    }

    const content = await response.text();

    if (!content || content.trim().length === 0) {
      throw new Error("Empty response");
    }

    // Basic validation - should be XML
    if (!content.trim().startsWith("<?xml")) {
      throw new Error("Response is not XML");
    }

    console.log(`   ✅ Downloaded ${Math.round(content.length / 1024)}KB`);
    return content;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error(`   ❌ Failed: ${message}`);
    throw error;
  }
}

/**
 * Compare two strings and return diff info
 */
function compareContent(oldContent: string | null, newContent: string): DiffResult {
  if (!oldContent) {
    return { changed: true, type: "new", message: "New file" };
  }

  if (oldContent === newContent) {
    return { changed: false, type: "unchanged", message: "No changes" };
  }

  const oldLines = oldContent.split("\n").length;
  const newLines = newContent.split("\n").length;
  const sizeDiff = newContent.length - oldContent.length;

  return {
    changed: true,
    type: "modified",
    message: `Modified (${sizeDiff > 0 ? "+" : ""}${sizeDiff} bytes, ${newLines - oldLines > 0 ? "+" : ""}${newLines - oldLines} lines)`,
  };
}

/**
 * Generate the schemas-data.ts file
 */
function generateSchemasDataFile(schemas: Schemas): void {
  const tsContent = `/**
 * Bundled XSD schemas - generated automatically by pnpm update-schemas
 *
 * DO NOT EDIT THIS FILE MANUALLY - it will be overwritten.
 *
 * This file contains all XSD schemas as embedded TypeScript string constants.
 * Used at runtime to avoid CORS issues and enable offline validation.
 *
 * Architecture:
 * - Source XSD files in src/schemas/*.xsd are the source of truth
 * - This file is generated from those XSD files
 * - Only this compiled JS file is used at runtime (XSD files are not accessed)
 * - XSD files are excluded from npm package to avoid duplication
 *
 * Generated from official Polish Ministry of Finance schemas.
 * Last updated: ${new Date().toISOString()}
 */

export const BUNDLED_SCHEMAS = ${JSON.stringify(schemas, null, 2)} as const;

export const SCHEMA_URLS = {
  main: 'http://crd.gov.pl/wzor/2025/06/25/13775/schemat.xsd',
  struktury: 'http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/DefinicjeTypy/StrukturyDanych_v10-0E.xsd',
  elementarne: 'http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/DefinicjeTypy/ElementarneTypyDanych_v10-0E.xsd',
  kody: 'http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/DefinicjeTypy/KodyKrajow_v10-0E.xsd'
} as const;
`;

  const dataFilePath = join(schemasDir, "schemas-data.ts");
  writeFileSync(dataFilePath, tsContent, "utf-8");
  console.log(`📝 Generated schemas-data.ts (${Math.round(tsContent.length / 1024)}KB)`);
}

/**
 * Main update function
 */
async function updateSchemas(): Promise<void> {
  console.log("🔄 KSeF Schema Update Tool");
  console.log("==========================\n");

  // Ensure schemas directory exists
  if (!existsSync(schemasDir)) {
    mkdirSync(schemasDir, { recursive: true });
    console.log(`📁 Created schemas directory: ${schemasDir}\n`);
  }

  const schemas: Partial<Schemas> = {};
  let hasChanges = false;

  // Download all schemas
  for (const [key, url] of Object.entries(SCHEMA_URLS) as Array<[keyof SchemaUrls, string]>) {
    const filename = SCHEMA_FILES[key];
    const filePath = join(schemasDir, filename);

    try {
      // Download new content
      const newContent = await downloadFile(url, `${key} schema`);

      // Read existing content if it exists
      let oldContent: string | null = null;
      if (existsSync(filePath)) {
        oldContent = readFileSync(filePath, "utf-8");
      }

      // Compare content
      const diff = compareContent(oldContent, newContent);
      console.log(`   📊 ${diff.message}`);

      if (diff.changed) {
        hasChanges = true;
        // Write new content
        writeFileSync(filePath, newContent, "utf-8");
        console.log(`   💾 Updated ${filename}`);
      }

      schemas[key] = newContent;
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      console.error(`\n❌ Failed to update ${key} schema:`);
      console.error(`   ${errorMessage}`);

      // Try to use existing file
      const filePath = join(schemasDir, SCHEMA_FILES[key]);
      if (existsSync(filePath)) {
        console.log(`   🔄 Using existing ${SCHEMA_FILES[key]}`);
        schemas[key] = readFileSync(filePath, "utf-8");
      } else {
        console.error(`   ⚠️  No existing file found, schema update incomplete`);
        process.exit(1);
      }
    }

    console.log(""); // Empty line for readability
  }

  // Validate we have all schemas
  const completeSchemas = schemas as Schemas;
  if (
    !completeSchemas.main ||
    !completeSchemas.struktury ||
    !completeSchemas.elementarne ||
    !completeSchemas.kody
  ) {
    console.error("❌ Not all schemas were loaded successfully");
    process.exit(1);
  }

  // Generate schemas-data.ts file
  generateSchemasDataFile(completeSchemas);

  // Summary
  console.log("\n📋 Update Summary");
  console.log("=================");

  if (hasChanges) {
    console.log("✅ Schemas updated successfully!");
    console.log("");
    console.log("📌 Next steps:");
    console.log("   1. Review the changes with git diff");
    console.log("   2. Test the validator: cd packages/validator && pnpm build && pnpm test");
    console.log("   3. Commit the updated schemas if tests pass");
  } else {
    console.log("✅ All schemas are up to date - no changes needed");
  }

  // Calculate total bundle size
  const totalSize = Object.values(completeSchemas).reduce(
    (sum, content) => sum + content.length,
    0,
  );
  console.log(`📦 Total bundle size: ${Math.round(totalSize / 1024)}KB`);
}

/**
 * Error handler
 */
process.on("unhandledRejection", (error: unknown) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error("\n💥 Unhandled error:", message);
  process.exit(1);
});

// Run the update
updateSchemas().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error("\n💥 Schema update failed:", message);
  process.exit(1);
});
